### ISSUE TITLE
Didn t work

### ISSUE THREAD

**Issue by Talap-creator** [MartinKondor/chat-with-document#1]
Upload error: PrismaClientKnownRequestError: 
Invalid prisma.$executeRaw() invocation:

Transaction API error: Transaction already closed: Could not perform operation.
    at Mn.handleRequestError (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:7753)
    at Mn.handleAndLogRequestError (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:7061)
    at Mn.request (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:6745)
    at async l (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:130:9633)
    at async eval (webpack-internal:///(rsc)/./app/api/upload/route.ts:47:17)
    at async Proxy._transactionWithCallback (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:130:8000)
    at async PUT (webpack-internal:///(rsc)/./app/api/upload/route.ts:45:9)
    at async C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55759
    at async eO.execute (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57093)
    at async doRender (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1345:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\start-server.js:141:13) {
  code: 'P2028',
  clientVersion: '5.20.0',
  meta: { error: 'Transaction already closed: Could not perform operation.' }
}
 PUT /api/upload 500 in 11421ms
Upload error: PrismaClientKnownRequestError: 
Invalid prisma.$executeRaw() invocation:

Transaction API error: Transaction already closed: Could not perform operation.
    at Mn.handleRequestError (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:7753)
    at Mn.handleAndLogRequestError (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:7061)
    at Mn.request (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:121:6745)
    at async l (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:130:9633)
    at async eval (webpack-internal:///(rsc)/./app/api/upload/route.ts:47:17)
    at async Proxy._transactionWithCallback (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\.prisma\client\runtime\library.js:130:8000)
    at async PUT (webpack-internal:///(rsc)/./app/api/upload/route.ts:45:9)
    at async C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:55759
    at async eO.execute (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:46527)
    at async eO.handle (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\compiled\next-server\app-route.runtime.dev.js:6:57093)
    at async doRender (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1345:42)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1567:28)
    at async DevServer.renderToResponseWithComponentsImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1475:28)
    at async DevServer.renderPageComponent (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1901:24)
    at async DevServer.renderToResponseImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:1939:32)
    at async DevServer.pipeImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:914:25)
    at async NextNodeServer.handleCatchallRenderRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\next-server.js:272:17)
    at async DevServer.handleRequestImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\base-server.js:810:17)
    at async C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\dev\next-dev-server.js:339:20
    at async Span.traceAsyncFn (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\trace\trace.js:154:20)
    at async DevServer.handleRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\dev\next-dev-server.js:336:24)
    at async invokeRender (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:173:21)
    at async handleRequest (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:350:24)
    at async requestHandlerImpl (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\router-server.js:374:13)
    at async Server.requestListener (C:\Users\Талап\Documents\GitHub\chat-with-document\node_modules\next\dist\server\lib\start-server.js:141:13) {
  code: 'P2028',
  clientVersion: '5.20.0',
  meta: { error: 'Transaction already closed: Could not perform operation.' }
}
 PUT /api/upload 500 in 9937ms

**Comment by MartinKondor** [comment]
did you install the project correctly?
https://github.com/MartinKondor/chat-with-document?tab=readme-ov-file#installation

**Comment by Talap-creator** [comment]
Yes
